### ISSUE TITLE
Gray background issue when long code and image size

### ISSUE THREAD

**Issue by kabeza** [picqer/php-barcode-generator#109]
Hi
I'm using this code to generate a barcode, and then I embed this image into DomPDF to output a PDF file which will contain the barcode, etc.

```
use Picqer\Barcode;
use Picqer\Barcode\BarcodeGeneratorPNG;
$generator = new BarcodeGeneratorPNG(); 
$img_codbarra = '<img src="data:image/png;base64,' . base64_encode($generator->getBarcode(CODE, $generator::TYPE_STANDARD_2_5,3,5,[0, 0, 0, 0.0])) . '" style="max-width:100%;width:auto;height:60px;">';

```

The problem is that the code is around 40, 50 characters.
The generated image occupies 100% pdf's width, but it has a "grey" background and I guess it is due the image must be narrowed/piled so it fits. And of course the barcode reader doesn't get it

Is there any workaround to make it work ?

Thanks a lot

**Comment by casperbakker** [comment]
Could you also post a screenshot of your generated PDF with the output?

If the image that is being rendered (before inserting into dompdf) from good enough quality? 

You could try to use SVG or HTML instead of PNG, that will add the barcode as a vector image to the PDF resulting in better quality.

Another hack I sometimes use with PDF's, is generating the image even bigger (so with a bigger widthFactor) to give more data in the image to render better PDF's and printouts.

**Comment by kabeza** [comment]
Hi @casperbakker 

The image quality with PNG generator is great. The problem is the space where the barcode must be inserted

I'm trying the HTML generator and is much more cleaner. The space is still a problem but I think I'll get it with some css

Thanks a lot for the tips

![imagen_716](https://user-images.githubusercontent.com/274856/93496975-43177a00-f8e6-11ea-925a-f52b37c27848.jpg)

**Comment by casperbakker** [comment]
Yes, this will always be hard with a lot of chars in the barcode. Not every bar can be represented by whole pixels, and anti aliasing making it a bit grey. If you have that many chars, maybe a 2D barcode is more appropriate, but not all scanners support 2D barcodes.
