### ISSUE TITLE
detect barcode type from given string

### ISSUE THREAD

**Issue by wnunezc** [picqer/php-barcode-generator#116]
mpdf need barcode type in string to print the barcode.

php-barcode-generator can retrive this information from given barcode string???

https://mpdf.github.io/reference/html-control-tags/barcode.html

**Comment by casperbakker** [comment]
No, that is not possible by no one. Because a barcode type is not about the text inside the barcode, but about the encoding from text to bars. The string ‘abc’ is valid in all barcode types that are not integer-only. 

You can choose code128 as this is the type that has support for the most chars and is variable in length.
