### ISSUE TITLE
Ideally i'd like to use this library on a Symfony 2.8 / PHP5.6 system

### ISSUE THREAD

**Issue by sterichards** [picqer/php-barcode-generator#120]
Are you aware of any incompatibles that may arise if I clone your project and remove the >PHP7 Composer requirement?

IE - Is there any code that isn't compatible with PHP5.6 that you are aware of?

**Comment by casperbakker** [comment]
I don't know from the top of my head. It was hard to get all the tests to work with version 5.6, but that could also be specifically because of the PHPUnit version.

There are previous versions that work fine with 5.6, I think if you install it on a system that supports 5.6 composer will use an older version that is compatible. For example [version 0.3](https://github.com/picqer/php-barcode-generator/releases/tag/v0.3). The interface was different back then, so you should use the readme from that version, but it should still create working barcodes.
