### ISSUE TITLE
Generating wrong PNG in CODE_128  

### ISSUE THREAD

**Issue by kakadong802** [picqer/php-barcode-generator#121]
Here is my code :

`require 'vendor/autoload.php';

$generator = new Picqer\Barcode\BarcodeGeneratorPNG();
file_put_contents('barcode.png', $generator->getBarcode('20010211100000021B', $generator::TYPE_CODE_128));`

it generate this barcode:  
![barcode](https://user-images.githubusercontent.com/70992401/105139643-7cc8ed80-5b31-11eb-825e-10d7d8d8b96f.png)

However the correct one should look like this one : 
![barcode (4)](https://user-images.githubusercontent.com/70992401/105139764-aaae3200-5b31-11eb-8e04-f9caa99ee8d8.gif)

Please Fix this error .  Thanks a lot .

**Comment by joeybab3** [comment]
The one generated does scan for the record

**Comment by casperbakker** [comment]
They are both correct. With Code 128 there are multiple ways to encode characters and to switch between A, B and C mode. It looks like the one from our library is more compact, probably because it has so many numbers and those can be encoded with 2 numbers together in 1 char, making the resulting barcode smaller. Because of the 'B' in the end we switch to a different mode for the last part, but the other barcode generator probably uses a single method that also supports the B.
