### ISSUE TITLE
GS1 - LICENSED UPC CODE

### ISSUE THREAD

**Issue by sadorect** [picqer/php-barcode-generator#148]
Thank you for the simple easy-to-use code. I understand that you need a license from GS1 to generate a UPC barcode. Where does that license feature in this code?

**Comment by casperbakker** [comment]
This library only does the translation of a string of characters (for example "049000060911") to a representation of bars in an image for barcode scanners to scan. A barcode scanner will always work in translating the bars back to the string of characters.

The barcode specification of Code128 can be used with any number of characters and you don't need any license.

The UPC barcodes from GS1 are special, because they are used in supermarkets and other stores. So it is best if Coca Cola and KitKat would use different codes for their products. That is were GS1 comes in. You can 'buy' a range of barcodes for your products. But what you buy in that license is only the right to use the numbers (the input string) for your products. You can get a license for the numbers 049000060911 - 049000060920 for example, to use on 10 different products.

But as long as you don't use it as barcodes on products to be scanned in stores, you can use whatever could you like.

Tip: if you just use some numbers for something other than real GS1 barcodes, don't use UPC barcodes. UPC barcodes are just Code128 barcodes, but with a very specific limit and only numbers can be used.
