### ISSUE TITLE
12 digit UPC-A code generating error

### ISSUE THREAD

**Issue by vishakha-simply** [picqer/php-barcode-generator#150]
Hello 
I'm trying to create a upc-A barcode with the standard 12 digits but it produces an error on some range of barcodes, scans others perfectly

An error happened (Picqer\\Barcode\\Exceptions\\InvalidCheckDigitException):

The checksum is not calculated properly and produces an error on some barcodes
![image](https://user-images.githubusercontent.com/59580756/159569313-6062b774-ea35-48d6-b2ae-d39a3b67ec49.png)

**Comment by casperbakker** [comment]
That means that the data you provided is not valid. The last part of the barcode is the 'checksum', a check if the barcode is rightly encoded. If you provide the data without the checksum, this library will calculate the checksum for you. But if you provide the data including the checksum, we will check that the checksum is right. Otherwise the resulting barcode will be invalid.

If you believe the checksum calculation is wrong, please provide complete examples and the results you were expecting.
