### ISSUE TITLE
Height & Width Issue

### ISSUE THREAD

**Issue by rushiwebonomics** [picqer/php-barcode-generator#8]
I am using picqer bar code generator for generating bar code. My requirement for bar code height is 26.45 pixels and width is 185.19 pixels. Height is adjustable. But I want width to be precise 185 or 186. How can I do that? I have adjusted height as 27 but How can i set the width of bar code of 186. Your early reply will be appreciated.

**Comment by casperbakker** [comment]
The widths are variable because different codes will have different space needs.

Best thing to do is creating a bigger image, then resize it down with GD yourself to the width you need. You can also crop the height after that to make sure you have the same width and height every time.

**Comment by ghost** [comment]
Why don't you just use % instead of px?

**Comment by casperbakker** [comment]
That is what this code is based on when I forked it and there is no practical reason to change it for now.

**Comment by ghost** [comment]
the practical reason is that right now it has a fixed size. I cannot print it on labes because it's huge. It's even bigger than iphone screens so it's neither mobile friendly. My POS prints label barcode which are 1cm wide. Yours are 5 cm wide. So that's the practical use.

**Comment by casperbakker** [comment]
Well, in practice this library only generates the image itself. You can embed the image on a HTML page with the img tag, and specify the height and width as you wish and it will reformat the image as needed.

It is even recommended to create a larger image and display it smaller, that way you can print the image with 300 dpi, instead of 72 dpi which will be used when you print an image from the browser directly.

If you really need it as an image, you can also resize it with GD after this library created the image.

So that is why there is no 'practical reason' for this whole library to be changed to work based on percentage then on pixels.

And if you think that is what needs to be done, you are free to fork this library and change it yourself.

**Comment by ghost** [comment]
Can you at least provide more demos/examples? You know, you didn't showed
us what this class can really do...

Il 07 mar 2017 12:16, "Casper Bakker" <notifications@github.com> ha scritto:

**Comment by casperbakker** [comment]
See the [Readme](https://github.com/picqer/php-barcode-generator/blob/master/Readme.md) for usage and even an example how to embed directly in an image tag.

I am not obliged to do your work. If you think this library is useful to you, you are free to use it. If you think it is complete garbage, that is also fine with me, just build your own.

**Comment by ghost** [comment]
Uhm nice approach. You are truly able to "sell" your work.

**Comment by casperbakker** [comment]
I am not trying to "sell" this work, you are not able to pay me money for this... We use it ourself and it works like a charm. It is here for anyone else to enjoy. If you do not enjoy it, that is fine with me but just do not tell me what I should do in my free time.
